-- MySQL Script generated by MySQL Workbench
-- Sat Nov  5 20:03:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_smartlab
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_smartlab` ;

-- -----------------------------------------------------
-- Schema db_smartlab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_smartlab` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_smartlab` ;

-- -----------------------------------------------------
-- Table `db_smartlab`.`tipo_analisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartlab`.`tipo_analisis` (
  `id_analisis` INT NOT NULL,
  `id_dni` INT NOT NULL,
  `id_hc` VARCHAR(45) NOT NULL,
  `fecha_analisis` DATETIME NOT NULL,
  `fecha_retiro` DATETIME NOT NULL,
  PRIMARY KEY (`id_analisis`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `id_analisis_UNIQUE` ON `db_smartlab`.`tipo_analisis` (`id_analisis` ASC) VISIBLE;

CREATE UNIQUE INDEX `id_hc_UNIQUE` ON `db_smartlab`.`tipo_analisis` (`id_hc` ASC) VISIBLE;

CREATE UNIQUE INDEX `fecha_analisis_UNIQUE` ON `db_smartlab`.`tipo_analisis` (`fecha_analisis` ASC) VISIBLE;

CREATE UNIQUE INDEX `fecha_retiro_UNIQUE` ON `db_smartlab`.`tipo_analisis` (`fecha_retiro` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_smartlab`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartlab`.`localidad` (
  `id_localidad` INT NOT NULL,
  `nombre_localidad` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_localidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `id_localidad_UNIQUE` ON `db_smartlab`.`localidad` (`id_localidad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_smartlab`.`tipo_dni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartlab`.`tipo_dni` (
  `id_tipo_doc` INT NOT NULL,
  `tipo_doc` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_doc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_smartlab`.`registro_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartlab`.`registro_paciente` (
  `id_dni` INT NOT NULL,
  `id_nombre` VARCHAR(45) NOT NULL,
  `id_apellido` VARCHAR(25) NOT NULL,
  `id_telefono` INT NOT NULL,
  `id_sexo` VARCHAR(1) NOT NULL,
  `fk_localidad` INT NULL DEFAULT NULL,
  `fk_tipo_doc` INT NOT NULL,
  PRIMARY KEY (`id_dni`),
  CONSTRAINT `fk_localidad`
    FOREIGN KEY (`fk_localidad`)
    REFERENCES `db_smartlab`.`localidad` (`id_localidad`),
  CONSTRAINT `fk_tipo_doc`
    FOREIGN KEY (`fk_tipo_doc`)
    REFERENCES `db_smartlab`.`tipo_dni` (`id_tipo_doc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `id_dni_UNIQUE` ON `db_smartlab`.`registro_paciente` (`id_dni` ASC) VISIBLE;

CREATE INDEX `fk_localidad_idx` ON `db_smartlab`.`registro_paciente` (`fk_localidad` ASC) VISIBLE;

CREATE INDEX `fk_tipo_doc_idx` ON `db_smartlab`.`registro_paciente` (`fk_tipo_doc` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_smartlab`.`hc_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartlab`.`hc_paciente` (
  `id_hc` INT NOT NULL,
  `id_dni` INT NOT NULL,
  `id_apellido` VARCHAR(25) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `id_prestación` INT NOT NULL,
  PRIMARY KEY (`id_hc`),
  CONSTRAINT `id_dni`
    FOREIGN KEY (`id_dni`)
    REFERENCES `db_smartlab`.`registro_paciente` (`id_dni`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `id_hc_UNIQUE` ON `db_smartlab`.`hc_paciente` (`id_hc` ASC) VISIBLE;

CREATE INDEX `id_dni_idx` ON `db_smartlab`.`hc_paciente` (`id_dni` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_smartlab`.`usuario_administrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartlab`.`usuario_administrativo` (
  `nombre_usuario` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `contraseña` VARCHAR(8) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `id_login` INT NOT NULL,
  `id_hc` INT NOT NULL,
  PRIMARY KEY (`id_login`),
  CONSTRAINT `id_hc`
    FOREIGN KEY (`id_hc`)
    REFERENCES `db_smartlab`.`hc_paciente` (`id_hc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `id_dni_UNIQUE` ON `db_smartlab`.`usuario_administrativo` (`id_hc` ASC) VISIBLE;

CREATE UNIQUE INDEX `contraseña_UNIQUE` ON `db_smartlab`.`usuario_administrativo` (`contraseña` ASC) VISIBLE;

CREATE UNIQUE INDEX `nombre_usuario_UNIQUE` ON `db_smartlab`.`usuario_administrativo` (`nombre_usuario` ASC) VISIBLE;

CREATE INDEX `id_login_idx` ON `db_smartlab`.`usuario_administrativo` (`id_login` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_smartlab`.`analisis_administrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartlab`.`analisis_administrativo` (
  `id` INT NOT NULL,
  `id_login` INT NOT NULL,
  `id_analisis` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_analisis`
    FOREIGN KEY (`id_analisis`)
    REFERENCES `db_smartlab`.`tipo_analisis` (`id_analisis`),
  CONSTRAINT `id_login`
    FOREIGN KEY (`id_login`)
    REFERENCES `db_smartlab`.`usuario_administrativo` (`id_login`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `id_UNIQUE` ON `db_smartlab`.`analisis_administrativo` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `id_login_UNIQUE` ON `db_smartlab`.`analisis_administrativo` (`id_login` ASC) VISIBLE;

CREATE UNIQUE INDEX `id_analisis_UNIQUE` ON `db_smartlab`.`analisis_administrativo` (`id_analisis` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_smartlab`.`analisis_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_smartlab`.`analisis_paciente` (
  `id_analisis` INT NOT NULL,
  `id_prestacion` INT NOT NULL,
  `fk_id_hc` INT NOT NULL,
  PRIMARY KEY (`id_analisis`),
  CONSTRAINT `fk_id_hc`
    FOREIGN KEY (`fk_id_hc`)
    REFERENCES `db_smartlab`.`hc_paciente` (`id_hc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `id_analisis_paciente_UNIQUE` ON `db_smartlab`.`analisis_paciente` (`id_analisis` ASC) VISIBLE;

CREATE UNIQUE INDEX `id_hc_UNIQUE` ON `db_smartlab`.`analisis_paciente` (`fk_id_hc` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
